-- Active: 1731384164792@@127.0.0.1@3306@aloha
-- 파일 테이블
DROP TABLE IF EXISTS `files`;

CREATE TABLE `files` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`p_table`	VARCHAR(100)	NOT NULL	COMMENT '부모테이블',
	`p_no`	BIGINT	NOT NULL	COMMENT '부모PK',
	`type`	ENUM('MAIN', 'SUB')	NOT NULL	DEFAULT 'SUB'	COMMENT '타입',
	`file_name`	TEXT	NOT NULL	COMMENT '파일명',
	`origin_name`	TEXT	NOT NULL	COMMENT '원본파일명',
	`file_path`	TEXT	NOT NULL	COMMENT '파일경로',
	`file_size`	BIGINT	NULL	DEFAULT 0	COMMENT '용량',
	`seq`	BIGINT	NULL	DEFAULT 0	COMMENT '순서',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
) COMMENT '파일';

SELECT *
FROM files
WHERE id In ('c0860e3c-72df-41f2-a7b6-07d457cf79da');

SELECT *
FROM files
WHERE no In (11, 12, 15);